### ISSUE TITLE
gcc 4.9: No more output is seen on the console after "Starting Kernel..."

### ISSUE THREAD

**Issue by wongsyrone** [wongsyrone/openwrt-1#44]
official gcc 4.9 and self-added 4.9 -------- kernel boot freeze

MIPS can use gcc 4.9 and works well
http://kmoving.blog.163.com/blog/static/20504919720123151533819/

it should be a linaro gcc bug
https://github.com/gcc-mirror/gcc/commits/linaro/gcc-4_9-branch

**Comment by wongsyrone** [comment]
someone says DTB not attached

**Comment by wongsyrone** [comment]
based on link: https://developer.ridgerun.com/wiki/index.php/Common_Problems_-_Linux_kernel_doesnt_boot
we need kernel console configuration, machine ID and well-built kernel image to boot, and kernel console information was coded in DTS file.

look for:
[ ] compile DTB correctly
[ ] compile kernel and make image correctly

**Comment by wongsyrone** [comment]
https://github.com/wongsyrone/openwrt-1/blob/master/target/linux/mvebu/patches-3.18/001-add_mamba_support.patch#L101     console info here, but this info not passed to linux kernel, maybe DTB corrupted or kernel image corrupted

**Comment by wongsyrone** [comment]
DT warning 
https://lists.ozlabs.org/pipermail/linuxppc-dev/2009-February/068170.html

**Comment by wongsyrone** [comment]
try
http://lists.infradead.org/pipermail/linux-arm-kernel/2014-January/226851.html

**Comment by wongsyrone** [comment]
try to add buildroot's gcc 4.9.x patches

**Comment by wongsyrone** [comment]
check openembedded patches
https://github.com/openembedded/oe-core/tree/master/meta/recipes-devtools/gcc/gcc-4.9

**Comment by wongsyrone** [comment]
Reported: https://dev.openwrt.org/ticket/19916

**Comment by wongsyrone** [comment]
Giving up, and waiting upstream fix

**Comment by wongsyrone** [comment]
bootargs = "console=ttyS0,115200";

**Comment by wongsyrone** [comment]
finally https://github.com/openwrt-mirror/openwrt/commit/53a77a939215c571f27c44c436cf5f715ffc6235 , waiting......

**Comment by wongsyrone** [comment]
switching to self-added gcc 5.1 and need test

**Comment by wongsyrone** [comment]
failed on gcc 4.9, 5.1 and 5.2

**Comment by wongsyrone** [comment]
Still broken on official GCC 5.2.0

**Comment by plntyk** [comment]
can you try to insert / add to KCFLAGS (i dont know where - probably somewhere in kernel make templates)
```
-fno-ipa-sra
```
source: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65932

**Comment by wongsyrone** [comment]
Thanks, I will try.

**Comment by wongsyrone** [comment]
@plntyk 
Please refer to https://github.com/wongsyrone/openwrt-1/commit/35308f2435ec75192324d68817e7702e3b257e71 and https://github.com/wongsyrone/openwrt-1/commit/93c0a5173414cfa7684547de3c3a1f3dc4240383
If you want to send these changes to OpenWrt's mailing list, feel free to do it.

**Comment by wongsyrone** [comment]
nbd pushed a better solution from gcc guys, I will revert my changes.
