### ISSUE TITLE
musl

### ISSUE THREAD

**Issue by leenchan** [wongsyrone/openwrt-1#53]
请问 你的 chinadns 在 trunk musl 编译后，能正常工作吗？

**Comment by wongsyrone** [comment]
我没用过，不过发布出去的固件没有接收到不能用的反馈

**Comment by leenchan** [comment]
可否分享一下你的固件 测试一下，我编译成功，但是不能正常工作 或者单独ar71xx 的ChinaDns 单独 ipk.

**Comment by wongsyrone** [comment]
固件目前有qihoo c301和linksys wrt1900ac，你要哪个

**Comment by wongsyrone** [comment]
https://copy.com/x9JMKlZ01Ul8FX42
@leenchan  musl-libc + gcc 4.8

**Comment by wongsyrone** [comment]
@leenchan  刚问了，用我固件的说chinadns可以正常用，所以应该是没问题的，先关掉了

**Comment by wongsyrone** [comment]
@leenchan  qihoo 360 c301 FW: https://copy.com/Q17sBhlJRN9puzy8

**Comment by wongsyrone** [comment]
done in https://github.com/wongsyrone/openwrt-1/commit/63d84f82e758299b45ff661c64efba1dc9822d31
