### ISSUE TITLE
网速高了路由器假死

### ISSUE THREAD

**Issue by kuoruan** [wongsyrone/openwrt-1#68]
多拨5次之后，只要网速维持在3M/s左右，一段时间后就会断网，路由器没响应，后台也没办法进去了。是不是路由器配置低了，？请问这个问题有好的解决方法么？

**Comment by wongsyrone** [comment]
什么型号，硬件配置是什么

**Comment by kuoruan** [comment]
极路由HC5661 128内存 16M闪存 7620a

**Comment by wongsyrone** [comment]
如果不用多拨没事就是mwan3或者其他软件的问题

**Comment by kuoruan** [comment]
请问一下，编译最新版，mwan负载均衡接口全部显示离线，但是虚拟接口正常拨号，网速也叠加了的，这是Bug么？
再有就是，固件版本显示unknown又是哪里造成的？

**Comment by wongsyrone** [comment]
状态获取那部分看对应的sh和luci的cbi代码；另一个不清楚，make dirclean之后重新编译

**Comment by kuoruan** [comment]
make dirclean重新编译后也不行

**Comment by wongsyrone** [comment]
你用的是我最新的代码么

**Comment by kuoruan** [comment]
好吧，为了防止出问题，我从Ubuntu换成Centos之后，又重新编译了一次，问题依旧

**Comment by kuoruan** [comment]
唯一和以前不用的是，我是用的 svn co https://github.com/wongsyrone/openwrt-1

**Comment by wongsyrone** [comment]
这个和你用哪个发行版没关系，和vcs更没关系

**Comment by kuoruan** [comment]
我用git clone不用svn重新下了一份源码,编译后版本号正常了，但是mwan还是所有接口离线。

**Comment by wongsyrone** [comment]
mwan因为我不用，所以你要自己看代码解决
