### ISSUE TITLE
TP-Link TL-WR2041N v1 config缺失

### ISSUE THREAD

**Issue by lzz5235** [wongsyrone/openwrt-1#91]
我使用你的固件刷了路由器TP-Link TL-WR2041N v1，但是默认没有安装upnpd，求一份完整的config配置，包括你先前选中的内核模块，luci等，准备重新编译固件。

**Comment by wongsyrone** [comment]
https://github.com/wongsyrone/openwrt-1/tree/master/cfg
另外这个repo已经废弃了，不会再更新
